language: elixir
sudo: false
os:
  - windows
  - macos
  - linux
elixir:
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - os: windows
script:
  - if [[ "$TRAVIS_OS_NAME" = 'windows' ]]; then ./bin/build_win32; else ./bin/build; fi
notifications:
  recipients:
    - paulschoenfelder@fastmail.com
    - chris@chrishildebrand.net
